.gitignore
Makefile
README.md
routes/api.js

https://motainteam.atlassian.net/browse/OFWEB-840

added makefile + small logs [OFWEB-840]

---

routes/api.js

user agent string fix

---

.gitignore
package.json
routes/api.js
routes/photobooth.js
routes/share.js
server.js
service/phantomJs.js
views/photobooth/base.ect
views/photobooth/cms/cms.ect
views/photobooth/cms/native.ect
views/share/base.ect

https://motainteam.atlassian.net/browse/OFWEB-875
Prototype for server side rendering for sharing. Code refactor.

prototype of news sharing with server side rendering [OFWEB-875]

---

service/phantomJs.js

https://motainteam.atlassian.net/browse/OFWEB-877

prevent google analytics load when taking screenshot [OFWEB-877]

---

routes/share.js
server.js
service/phantomJs.js

Log all requests respond time.

universal request logger - log all request response time

---

service/phantomJs.js

Test to see if waiting for page to be finished loading helps in rendering.

added some checking that page is ready

---

service/phantomJs.js

Reverts Onefootball/PhotoBoothApi#15

Revert b5c9483d0388b19f0bb79091e064878a930b7232

---

service/phantomJs.js

Reverts Onefootball/PhotoBoothApi#14

Revert 89757ed633af43f788ba19fbc7c8b35bfcacfcc5

---

service/phantomJs.js

Try to kill phantomjs child process after is done.

attempt to kill phantomjs child process

---

service/phantomJs.js

Reverts Onefootball/PhotoBoothApi#19
I need to add logs to stderror output as well.

Revert baeb41926388b58766320fe72b3c1cf9d936187d

---

service/phantomJs.js

Reverts Onefootball/PhotoBoothApi#21
That does not work, api keeps restarting, will check what is going on and open new PR.

Revert 4a5770250dca0f8c549f0e7fb6c241805158b65b

---

service/phantomJs.js

No Jira issue. We can't just kill phantom, usually it seems it exits normally, when we call ph.exit (). So I just cleaned it up a bit, to exit on error as well. And to log a when it exits.

log on exit, exit also on fail

---

public/robots.txt
server.js

Added robots.txt to photobooth. 
I am only testing if that could be the reason why image is not shown.

added robots.txt + log some extra info

---

routes/api.js

https://motainteam.atlassian.net/browse/OFWEB-923|
Test that old urls still work. And try to passed them not encoded.

handle not encoded urls [OFWEB-923]

---

Makefile

	modified:   Makefile

---

server.js

Testing cachine issues with Adrien. No Jira ticket.

timestam + headers added to log

---

epazote.yml
service/phantomJs.js

https://motainteam.atlassian.net/browse/OFWEB-1018

add epazote health check file [OFWEB-1018]

---

epazote.yml

[I] reformat epazote file (NO JIRA TICKET)

---

README.md
config/config.js
config/config.json
factory/S3.js
package.json
routes/api.js
service/imageService.js
service/phantomJs.js

Added optional amazon s3 catching.

[F] added optional s3 amazon caching (OFWEB-968)

---

README.md
config/config.js
config/config.json
factory/S3.js
package.json
routes/api.js
service/imageService.js
service/phantomJs.js

Refactored the code to support the latest version of phantomjs-node package.

[F] Update phantomjs-node version to 2.x (OFWEB-1082)

---

config/config.json
server.js

Configurable way to ignore some requests from being logged.
You'll find the proper configuration within the config.json.

[I] Add mechanism to to skip logging some requests (OFWEB-1044)
